# -*- coding: utf-8 -*-
"""215103238.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QMZG21mEs0qGlNiVO-faLRinh1aWYfkD
"""

"""
SAS821S LAB 2 – COMPLETE PYTHON ANALYSIS
Parts B1 through D

Run this script from the directory containing the CSV files.
The script does not modify original datasets. It creates derived copies,
prints outputs for every section, saves plots, and exports top_15_high_risk_sessions.csv.
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    precision_score, recall_score, f1_score, roc_auc_score
)

# ============================================================
# 0. SETUP AND DATA LOADING
# ============================================================

DATA = Path.cwd()
OUTPUT = DATA / "lab2_outputs"
OUTPUT.mkdir(exist_ok=True)

def load_csv(original_name, *fallbacks, parse_dates=None):
    candidates = [original_name, *fallbacks]
    for name in candidates:
        path = DATA / name
        if path.exists():
            return pd.read_csv(path, parse_dates=parse_dates)
    raise FileNotFoundError(f"Could not find {original_name}. Checked: {candidates}")

employees = load_csv("ofs_employee_directory.csv", "ofs_employee_directory(2).csv")
assets = load_csv("ofs_asset_inventory.csv", "ofs_asset_inventory(2).csv")
email = load_csv("ofs_email_gateway_logs.csv", "ofs_email_gateway_logs(2).csv",
                 parse_dates=["timestamp"])
vpn = load_csv("ofs_vpn_authentication_logs.csv", "ofs_vpn_authentication_logs(2).csv",
               parse_dates=["timestamp"])
endpoint = load_csv("ofs_endpoint_process_logs.csv", "ofs_endpoint_process_logs(2).csv",
                    parse_dates=["timestamp"])
file_access = load_csv("ofs_file_access_logs.csv", "ofs_file_access_logs(2).csv",
                       parse_dates=["timestamp"])
proxy = load_csv("ofs_proxy_dlp_logs.csv", "ofs_proxy_dlp_logs(2).csv",
                 parse_dates=["timestamp"])
intel = load_csv("ofs_threat_intelligence.csv", "ofs_threat_intelligence(2).csv",
                 parse_dates=["first_seen", "last_updated"])
training = load_csv("ofs_access_session_training.csv", "ofs_access_session_training(3).csv",
                    parse_dates=["session_start"])
investigation = load_csv("ofs_access_session_investigation.csv", "ofs_access_session_investigation(3).csv",
                         parse_dates=["session_start"])
policy = load_csv("ofs_access_policy_matrix.csv", "ofs_access_policy_matrix(2).csv")

print("\n" + "=" * 75)
print("SAS821S LAB 2 – COMPLETE PYTHON ANALYSIS")
print("=" * 75)

print("\nDATASET ROW COUNTS")
for name, frame in {
    "employees": employees, "assets": assets, "email": email, "vpn": vpn,
    "endpoint": endpoint, "file_access": file_access, "proxy": proxy,
    "intel": intel, "policy": policy, "training": training,
    "investigation": investigation
}.items():
    print(f"{name:18s}: {len(frame):5d} rows")

# ============================================================
# PART B1 – DATA PREPARATION AND DERIVED FIELDS
# ============================================================

print("\n" + "=" * 75)
print("PART B1 – DATA PREPARATION AND DERIVED FIELDS")
print("=" * 75)

# Work on copies so original CSVs are not changed.
vpn_b1 = vpn.copy()
file_b1 = file_access.copy()
proxy_b1 = proxy.copy()
endpoint_b1 = endpoint.copy()
training_b1 = training.copy()
investigation_b1 = investigation.copy()

# Time-derived fields
for df, ts in [
    (vpn_b1, "timestamp"),
    (file_b1, "timestamp"),
    (proxy_b1, "timestamp"),
    (endpoint_b1, "timestamp"),
]:
    df["hour"] = df[ts].dt.hour
    df["day_of_week"] = df[ts].dt.day_name()
    df["weekend"] = (df[ts].dt.dayofweek >= 5).astype(int)
    df["off_hours"] = ((df["hour"] < 7) | (df["hour"] >= 18)).astype(int)

# File-transfer fields
file_b1["download_mb"] = file_b1["bytes_transferred"].fillna(0) / (1024 ** 2)
proxy_b1["upload_mb"] = proxy_b1["bytes_out"].fillna(0) / (1024 ** 2)

# Employee lookup
emp_lookup = employees.set_index("user_id")

def lookup_employee(user_id, field, default=np.nan):
    try:
        return emp_lookup.loc[user_id, field]
    except KeyError:
        return default

for df in [vpn_b1, file_b1, proxy_b1]:
    df["department"] = df["user_id"].map(employees.set_index("user_id")["department"])
    df["role"] = df["user_id"].map(employees.set_index("user_id")["role"])
    df["risk_tier"] = df["user_id"].map(employees.set_index("user_id")["risk_tier"])

# New geography/device indicators from VPN history
vpn_b1 = vpn_b1.sort_values(["user_id", "timestamp"]).copy()
vpn_b1["new_device_derived"] = (
    vpn_b1.groupby("user_id")["device_id"]
    .transform(lambda s: ~s.eq(s.shift()).fillna(False))
).astype(int)

vpn_b1["new_geography"] = (
    vpn_b1.groupby("user_id")["country"]
    .transform(lambda s: s.notna() & ~s.eq(s.ffill()).fillna(False))
).astype(int)

# Correct first occurrence behaviour: first observed device/geography is not treated as suspicious.
vpn_b1.loc[vpn_b1.groupby("user_id").head(1).index, "new_device_derived"] = 0
vpn_b1.loc[vpn_b1.groupby("user_id").head(1).index, "new_geography"] = 0

# Resource sensitivity and role mismatch from policy matrix
policy_roles = {}
for _, row in policy.iterrows():
    roles = str(row["authorised_departments_or_roles"]).split(";")
    policy_roles[row["resource_group"]] = [r.strip().lower() for r in roles]

def employee_authorised(user_id, resource_group):
    if pd.isna(resource_group):
        return False
    emp = emp_lookup.loc[user_id] if user_id in emp_lookup.index else None
    if emp is None:
        return False
    dept = str(emp["department"]).strip().lower()
    role = str(emp["role"]).strip().lower()
    permitted = [x.strip().lower() for x in str(emp["permitted_resource_groups"]).split(";")]
    group = str(resource_group).strip().lower()

    # Employee directory permission OR policy department/role permission.
    return group in permitted or dept in policy_roles.get(resource_group, []) or role in policy_roles.get(resource_group, [])

file_b1["resource_sensitivity"] = file_b1["resource_group"].map(
    policy.set_index("resource_group")["classification"]
).fillna(file_b1["sensitivity"])

file_b1["role_mismatch"] = [
    int(not employee_authorised(u, r))
    for u, r in zip(file_b1["user_id"], file_b1["resource_group"])
]

# Session-level derived fields
for df in [training_b1, investigation_b1]:
    df["hour"] = df["session_start"].dt.hour
    df["day_of_week"] = df["session_start"].dt.day_name()
    df["weekend_derived"] = (df["session_start"].dt.dayofweek >= 5).astype(int)
    df["off_hours_derived"] = ((df["hour"] < 7) | (df["hour"] >= 18)).astype(int)
    df["download_mb"] = df["bytes_downloaded_mb"]
    df["upload_mb"] = df["data_upload_mb"]
    df["resource_sensitivity"] = np.select(
        [df["sensitive_resources"] >= 4, df["sensitive_resources"] >= 1],
        ["Restricted/High", "Confidential/Medium"],
        default="Internal/Low"
    )
    df["role_mismatch_derived"] = df["privilege_mismatch"].astype(int)

print("\nB1.1 Derived fields created:")
print(" - hour")
print(" - day_of_week")
print(" - weekend / weekend_derived")
print(" - off_hours / off_hours_derived")
print(" - new_device_derived")
print(" - new_geography")
print(" - download_mb")
print(" - upload_mb")
print(" - resource_sensitivity")
print(" - role_mismatch / role_mismatch_derived")

print("\nB1.2 File-access sample with derived fields:")
print(file_b1[
    ["event_id", "timestamp", "user_id", "resource_group",
     "resource_sensitivity", "download_mb", "off_hours", "role_mismatch"]
].head(10).to_string(index=False))

print("\nB1.3 VPN sample with new-device/geography indicators:")
print(vpn_b1[
    ["event_id", "timestamp", "user_id", "country", "city",
     "device_id", "new_device_derived", "new_geography", "off_hours"]
].head(10).to_string(index=False))

# ============================================================
# PART B2 – PEER BASELINES AND INVESTIGATION SUMMARIES
# ============================================================

print("\n" + "=" * 75)
print("PART B2 – PEER-GROUP BASELINES AND INVESTIGATION SUMMARIES")
print("=" * 75)

# Peer baseline by department using training data.
peer = (
    training_b1.groupby("department")
    .agg(
        sessions=("session_id", "count"),
        mean_download_mb=("bytes_downloaded_mb", "mean"),
        median_download_mb=("bytes_downloaded_mb", "median"),
        p95_download_mb=("bytes_downloaded_mb", lambda s: s.quantile(.95)),
        mean_upload_mb=("data_upload_mb", "mean"),
        mean_sensitive_resources=("sensitive_resources", "mean"),
        mean_files_read=("files_read", "mean"),
    )
    .reset_index()
)

print("\nB2.1 Peer-group baseline by department:")
print(peer.to_string(index=False))

# User baseline
user_baseline = (
    training_b1.groupby(["user_id", "department"])
    .agg(
        sessions=("session_id", "count"),
        mean_download_mb=("bytes_downloaded_mb", "mean"),
        p95_download_mb=("bytes_downloaded_mb", lambda s: s.quantile(.95)),
        mean_upload_mb=("data_upload_mb", "mean"),
        mean_sensitive=("sensitive_resources", "mean"),
    )
    .reset_index()
)

print("\nB2.2 Top users by total download in training data:")
user_download = (
    training_b1.groupby("user_id", as_index=False)["bytes_downloaded_mb"]
    .sum()
    .rename(columns={"bytes_downloaded_mb": "total_download_mb"})
    .sort_values("total_download_mb", ascending=False)
)
print(user_download.head(10).to_string(index=False))

# Investigation summaries
inv_summary = investigation_b1.copy()
inv_summary["risk_indicator_count"] = (
    (inv_summary["new_device"] == 1).astype(int)
    + (inv_summary["off_hours"] == 1).astype(int)
    + (inv_summary["failed_logins_30m"] >= 3).astype(int)
    + (inv_summary["mfa_denials"] >= 2).astype(int)
    + (inv_summary["sensitive_resources"] >= 2).astype(int)
    + (inv_summary["denied_accesses"] >= 1).astype(int)
    + (inv_summary["impossible_travel"] == 1).astype(int)
    + (inv_summary["privilege_mismatch"] == 1).astype(int)
    + (inv_summary["data_upload_mb"] >= 100).astype(int)
)

print("\nB2.3 Investigation sessions with the most simultaneous risk indicators:")
print(
    inv_summary.sort_values(
        ["risk_indicator_count", "data_upload_mb", "bytes_downloaded_mb"],
        ascending=False
    )[[
        "session_id", "user_id", "session_start", "risk_indicator_count",
        "new_device", "off_hours", "failed_logins_30m", "mfa_denials",
        "sensitive_resources", "denied_accesses", "data_upload_mb",
        "impossible_travel", "privilege_mismatch"
    ]].head(15).to_string(index=False)
)

# Visualisations – at least three investigation questions.
print("\nB2.4 Creating three investigation visualisations...")

# Figure 1
top10 = user_download.head(10).sort_values("total_download_mb")
plt.figure(figsize=(9, 6))
plt.barh(top10["user_id"], top10["total_download_mb"])
plt.xlabel("Downloaded MB")
plt.ylabel("User")
plt.title("B2 – Top 10 Users by Download Volume")
plt.tight_layout()
plt.savefig(OUTPUT / "B2_1_top_download_users.png", dpi=150)
plt.show()
print("Figure 1 saved: B2_1_top_download_users.png")

# Figure 2
dept_risk = (
    investigation_b1.groupby("department")
    .agg(
        mean_process_risk=("process_risk_score", "mean"),
        mean_destination_risk=("destination_risk_score", "mean")
    )
    .sort_values("mean_process_risk", ascending=False)
)
plt.figure(figsize=(10, 6))
x = np.arange(len(dept_risk))
width = 0.38
plt.bar(x - width/2, dept_risk["mean_process_risk"], width, label="Process risk")
plt.bar(x + width/2, dept_risk["mean_destination_risk"], width, label="Destination risk")
plt.xticks(x, dept_risk.index, rotation=45, ha="right")
plt.ylabel("Mean risk score")
plt.title("B2 – Process and Destination Risk by Department")
plt.legend()
plt.tight_layout()
plt.savefig(OUTPUT / "B2_2_department_risk.png", dpi=150)
plt.show()
print("Figure 2 saved: B2_2_department_risk.png")

# Figure 3
plt.figure(figsize=(9, 6))
plt.scatter(
    investigation_b1["data_upload_mb"],
    investigation_b1["destination_risk_score"],
    alpha=0.65
)
plt.xlabel("Data Upload (MB)")
plt.ylabel("Destination Risk Score")
plt.title("B2 – Outbound Upload Volume vs Destination Risk")
plt.tight_layout()
plt.savefig(OUTPUT / "B2_3_upload_vs_destination_risk.png", dpi=150)
plt.show()
print("Figure 3 saved: B2_3_upload_vs_destination_risk.png")

# ============================================================
# PART B3 – TRANSPARENT RULE-BASED RISK SCORE
# ============================================================

print("\n" + "=" * 75)
print("PART B3 – TRANSPARENT RULE-BASED RISK SCORE")
print("=" * 75)

# At least four explicit indicators.
# Maximum possible = 100.
def rule_score(df):
    out = df.copy()

    out["r_off_hours"] = (out["off_hours"] == 1).astype(int)
    out["r_new_device"] = (out["new_device"] == 1).astype(int)
    out["r_failed_logins"] = (out["failed_logins_30m"] >= 3).astype(int)
    out["r_mfa_denials"] = (out["mfa_denials"] >= 2).astype(int)
    out["r_sensitive"] = (out["sensitive_resources"] >= 2).astype(int)
    out["r_denied_access"] = (out["denied_accesses"] >= 1).astype(int)
    out["r_impossible_travel"] = (out["impossible_travel"] == 1).astype(int)
    out["r_privilege_mismatch"] = (out["privilege_mismatch"] == 1).astype(int)
    out["r_large_upload"] = (out["data_upload_mb"] >= 100).astype(int)
    out["r_process_risk"] = (out["process_risk_score"] >= 70).astype(int)
    out["r_destination_risk"] = (out["destination_risk_score"] >= 70).astype(int)
    out["r_peer_deviation"] = (out["peer_deviation_score"] >= 5).astype(int)

    # Transparent weights.
    out["rule_score"] = (
        out["r_off_hours"] * 5
        + out["r_new_device"] * 8
        + out["r_failed_logins"] * 8
        + out["r_mfa_denials"] * 8
        + out["r_sensitive"] * 10
        + out["r_denied_access"] * 5
        + out["r_impossible_travel"] * 12
        + out["r_privilege_mismatch"] * 12
        + out["r_large_upload"] * 12
        + out["r_process_risk"] * 5
        + out["r_destination_risk"] * 5
        + out["r_peer_deviation"] * 5
    )

    out["risk_level"] = pd.cut(
        out["rule_score"],
        bins=[-1, 19, 39, 59, np.inf],
        labels=["Low", "Medium", "High", "Critical"]
    )
    return out

investigation_scored = rule_score(investigation_b1)

print("\nB3.1 Risk-score rule definition:")
rules = pd.DataFrame({
    "Indicator": [
        "Off-hours", "New device", ">=3 failed logins/30m", ">=2 MFA denials",
        ">=2 sensitive resources", "Denied access", "Impossible travel",
        "Privilege mismatch", ">=100 MB upload", "Process risk >=70",
        "Destination risk >=70", "Peer deviation >=5"
    ],
    "Weight": [5, 8, 8, 8, 10, 5, 12, 12, 12, 5, 5, 5]
})
print(rules.to_string(index=False))

print("\nB3.2 Risk-level distribution:")
print(investigation_scored["risk_level"].value_counts().sort_index().to_string())

print("\nB3.3 Top 15 sessions by transparent rule score:")
top15_rule = investigation_scored.sort_values(
    ["rule_score", "data_upload_mb", "bytes_downloaded_mb"],
    ascending=False
).head(15)

print(top15_rule[
    ["session_id", "user_id", "session_start", "rule_score", "risk_level",
     "off_hours", "new_device", "failed_logins_30m", "mfa_denials",
     "sensitive_resources", "denied_accesses", "data_upload_mb",
     "process_risk_score", "destination_risk_score",
     "impossible_travel", "privilege_mismatch"]
].to_string(index=False))

# False positives / missed behaviour against labels in training data.
training_scored = rule_score(training_b1)
# Rule threshold: High/Critical = positive.
training_scored["rule_pred"] = (training_scored["rule_score"] >= 40).astype(int)

tn, fp, fn, tp = confusion_matrix(
    training_scored["label"], training_scored["rule_pred"], labels=[0, 1]
).ravel()

print("\nB3.4 False-positive and missed-behaviour check (training data):")
print(f"True positives : {tp}")
print(f"False positives: {fp}")
print(f"True negatives : {tn}")
print(f"Missed positives (false negatives): {fn}")
print(f"Rule precision : {precision_score(training_scored['label'], training_scored['rule_pred'], zero_division=0):.3f}")
print(f"Rule recall    : {recall_score(training_scored['label'], training_scored['rule_pred'], zero_division=0):.3f}")
print("Interpretation: false positives are benign sessions flagged by the rule; missed behaviour is labelled-risk sessions not flagged.")

# ============================================================
# PART D1 – ACCESS-SESSION CLASSIFIER
# ============================================================

print("\n" + "=" * 75)
print("PART D1 – ACCESS-SESSION CLASSIFIER")
print("=" * 75)

feature_cols = [
    "new_device", "off_hours", "failed_logins_30m", "mfa_denials",
    "mfa_approvals", "unique_resources", "sensitive_resources",
    "denied_accesses", "files_read", "bytes_downloaded_mb",
    "data_upload_mb", "process_risk_score", "destination_risk_score",
    "peer_deviation_score", "impossible_travel", "privilege_mismatch"
]

X = training_b1[feature_cols].fillna(0)
y = training_b1["label"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

clf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    min_samples_leaf=2
)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:, 1]

print("\nC1.1 Model: Random Forest")
print(f"Training rows: {len(X_train)}")
print(f"Testing rows : {len(X_test)}")
print(f"Accuracy     : {accuracy_score(y_test, y_pred):.3f}")
print(f"Precision    : {precision_score(y_test, y_pred, zero_division=0):.3f}")
print(f"Recall       : {recall_score(y_test, y_pred, zero_division=0):.3f}")
print(f"F1-score     : {f1_score(y_test, y_pred, zero_division=0):.3f}")
print(f"ROC-AUC      : {roc_auc_score(y_test, y_prob):.3f}")

print("\nC1.2 Classification report:")
print(classification_report(y_test, y_pred, digits=3, zero_division=0))

print("C1.3 Confusion matrix:")
print(pd.DataFrame(
    confusion_matrix(y_test, y_pred),
    index=["Actual 0", "Actual 1"],
    columns=["Predicted 0", "Predicted 1"]
).to_string())

importance = pd.DataFrame({
    "feature": feature_cols,
    "importance": clf.feature_importances_
}).sort_values("importance", ascending=False)

print("\nC1.4 Feature importance:")
print(importance.to_string(index=False))

plt.figure(figsize=(9, 6))
imp = importance.head(10).sort_values("importance")
plt.barh(imp["feature"], imp["importance"])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("C1 – Top 10 Random Forest Features")
plt.tight_layout()
plt.savefig(OUTPUT / "C1_feature_importance.png", dpi=150)
plt.show()
print("Figure saved: C1_feature_importance.png")

# ============================================================
# PART D2 – SCORE INVESTIGATION SESSIONS AND EXPORT TOP 15
# ============================================================

print("\n" + "=" * 75)
print("PART D2 – INVESTIGATION SESSION CLASSIFICATION AND TOP 15")
print("=" * 75)

X_inv = investigation_b1[feature_cols].fillna(0)
investigation_scored["model_probability"] = clf.predict_proba(X_inv)[:, 1]
investigation_scored["model_prediction"] = clf.predict(X_inv)

# Combined ranking: transparent rule score first, model probability as supporting evidence.
investigation_scored["combined_priority"] = (
    investigation_scored["rule_score"] / investigation_scored["rule_score"].max()
    + investigation_scored["model_probability"]
)

top15 = investigation_scored.sort_values(
    ["combined_priority", "rule_score", "model_probability"],
    ascending=False
).head(15).copy()

export_cols = [
    "session_id", "session_start", "user_id", "department",
    "source_country", "new_device", "off_hours", "failed_logins_30m",
    "mfa_denials", "mfa_approvals", "unique_resources",
    "sensitive_resources", "denied_accesses", "files_read",
    "bytes_downloaded_mb", "data_upload_mb", "process_risk_score",
    "destination_risk_score", "peer_deviation_score",
    "impossible_travel", "privilege_mismatch",
    "rule_score", "risk_level", "model_probability",
    "model_prediction", "combined_priority"
]
top15[export_cols].to_csv(OUTPUT / "top_15_high_risk_sessions.csv", index=False)

print("\nC2.1 Top 15 investigation sessions:")
print(top15[export_cols].to_string(index=False))
print("\nC2.2 Export created:")
print(OUTPUT / "top_15_high_risk_sessions.csv")

# ============================================================
# PART C1 – CROSS-SOURCE EVENT CORRELATION / INCIDENT TIMELINE
# ============================================================

print("\n" + "=" * 75)
print("PART C1 – CROSS-SOURCE EVENT CORRELATION AND TIMELINE")
print("=" * 75)

incident_user = "mhaingura"
incident_start = pd.Timestamp("2026-09-11 16:50:00")
incident_end = pd.Timestamp("2026-09-12 01:00:00")

timeline = []

# Email
for _, r in email[
    (email["recipient"] == incident_user) &
    (email["timestamp"].between(incident_start, incident_end))
].sort_values("timestamp").iterrows():
    timeline.append({
        "timestamp": r["timestamp"], "event_id": r["event_id"], "source": "Email",
        "user": incident_user,
        "event": f"Email: {r['subject']} | verdict={r['verdict']} | URL={r['url']}"
    })

# Endpoint
for _, r in endpoint[
    (endpoint["user_id"] == incident_user) &
    (endpoint["timestamp"].between(incident_start, incident_end))
].sort_values("timestamp").iterrows():
    timeline.append({
        "timestamp": r["timestamp"], "event_id": r["event_id"], "source": "Endpoint",
        "user": incident_user,
        "event": f"Process {r['process_name']} parent={r['parent_process']} risk={r['risk_level']} action={r['edr_action']}"
    })

# VPN
for _, r in vpn[
    (vpn["user_id"] == incident_user) &
    (vpn["timestamp"].between(incident_start, incident_end))
].sort_values("timestamp").iterrows():
    timeline.append({
        "timestamp": r["timestamp"], "event_id": r["event_id"], "source": "VPN",
        "user": incident_user,
        "event": f"VPN {r['result']} MFA={r['mfa_result']} country={r['country']} city={r['city']} device={r['device_id']}"
    })

# File access
for _, r in file_access[
    (file_access["user_id"] == incident_user) &
    (file_access["timestamp"].between(incident_start, incident_end))
].sort_values("timestamp").iterrows():
    if (
        r["resource_group"] in ["CUSTOMER_EXPORT", "HR_CONFIDENTIAL", "PAYROLL_READ"]
        or r["status"] == "DENIED"
        or r["bytes_transferred"] > 5_000_000
    ):
        timeline.append({
            "timestamp": r["timestamp"], "event_id": r["event_id"], "source": "File Access",
            "user": incident_user,
            "event": f"{r['action']} {r['resource_group']} status={r['status']} bytes={r['bytes_transferred']} path={r['resource_path']}"
        })

# Proxy / DLP
for _, r in proxy[
    (proxy["user_id"] == incident_user) &
    (proxy["timestamp"].between(incident_start, incident_end))
].sort_values("timestamp").iterrows():
    if r["bytes_out"] > 1_000_000 or r["dlp_rule"] != "NONE":
        timeline.append({
            "timestamp": r["timestamp"], "event_id": r["event_id"], "source": "Proxy/DLP",
            "user": incident_user,
            "event": f"{r['method']} {r['destination_domain']} bytes_out={r['bytes_out']} DLP={r['dlp_rule']} action={r['action']}"
        })

timeline_df = pd.DataFrame(timeline).sort_values("timestamp")

print("\nC3.1 Correlated incident timeline:")
if len(timeline_df):
    print(timeline_df.to_string(index=False))
else:
    print("No correlated events found in the selected incident window.")

timeline_df.to_csv(OUTPUT / "incident_correlated_timeline.csv", index=False)
print("\nTimeline export:", OUTPUT / "incident_correlated_timeline.csv")

# Threat intelligence matching
print("\nC3.2 Threat-intelligence matches:")
ti_matches = []

# Search IPs/domains/hashes in relevant logs against TI indicators.
for source_name, df, fields in [
    ("VPN", vpn, ["source_ip"]),
    ("Proxy/DLP", proxy, ["destination_domain", "destination_ip"]),
    ("Endpoint", endpoint, ["sha256"]),
    ("Email", email, ["url", "sender"])
]:
    for field in fields:
        if field not in df.columns:
            continue
        vals = set(df[field].dropna().astype(str))
        for _, t in intel.iterrows():
            indicator = str(t["indicator"])
            if indicator in vals:
                ti_matches.append({
                    "source": source_name,
                    "field": field,
                    "indicator": indicator,
                    "intel_id": t["intel_id"],
                    "confidence": t["confidence"],
                    "threat_actor": t["threat_actor"],
                    "tactic": t["tactic"],
                    "recommended_action": t["recommended_action"]
                })

ti_df = pd.DataFrame(ti_matches).drop_duplicates()
if len(ti_df):
    print(ti_df.to_string(index=False))
else:
    print("No exact threat-intelligence indicator matches found.")

# ============================================================
# PART C2/C3 – INCIDENT FINDINGS AND RESPONSE
# ============================================================

print("\n" + "=" * 75)
print("PART C2/C3 – INCIDENT RESPONSE AND RECOMMENDATIONS")
print("=" * 75)

# Identify the strongest investigation session for the incident.
case_rows = investigation_scored[
    investigation_scored["session_id"].astype(str).str.startswith("CASE-")
].sort_values("combined_priority", ascending=False)

print("\nD1. Priority case sessions:")
if len(case_rows):
    print(case_rows[
        ["session_id", "user_id", "session_start", "rule_score",
         "risk_level", "model_probability", "data_upload_mb",
         "bytes_downloaded_mb", "process_risk_score",
         "destination_risk_score", "impossible_travel",
         "privilege_mismatch"]
    ].to_string(index=False))
else:
    print("No CASE-* sessions found.")

# Evidence-based response actions.
response_actions = pd.DataFrame({
    "Priority": ["Immediate", "Immediate", "Immediate", "High", "High", "High", "Medium"],
    "Action": [
        "Contain affected account/session",
        "Isolate the affected endpoint and preserve EDR evidence",
        "Block confirmed malicious infrastructure and hashes from threat intelligence",
        "Revoke active sessions/tokens and reset credentials after evidence preservation",
        "Review and block malicious/phishing email indicators; identify recipients and clicks",
        "Review outbound transfer/DLP events and preserve relevant files/logs",
        "Strengthen MFA, privileged-access monitoring, DLP controls and alerting"
    ],
    "Reason": [
        "High-risk sessions show multiple independent indicators.",
        "Endpoint activity includes suspicious script execution and archive/cloud-transfer tooling.",
        "Threat intelligence identifies infrastructure associated with initial access/C2/exfiltration.",
        "Reduces continued account misuse while maintaining evidence.",
        "Email evidence provides a plausible phishing vector but should not be treated as proven initial access solely from timing.",
        "Large outbound transfers require containment and evidence preservation.",
        "Reduces recurrence and improves detection."
    ]
})

print("\nD2. Recommended response actions:")
print(response_actions.to_string(index=False))
response_actions.to_csv(OUTPUT / "part_D_response_actions.csv", index=False)

# Evidence assessment without overclaiming.
print("\nD3. Evidence-based assessment:")
print("1. The investigation identifies mhaingura as the primary high-risk account in the supplied case sessions.")
print("2. The strongest case evidence combines unusual VPN activity, suspicious endpoint processes,")
print("   restricted CUSTOMER_EXPORT access, and large outbound transfers to cloud infrastructure.")
print("3. The 17:02 phishing-related email and 17:03 endpoint execution are temporally correlated.")
print("4. The evidence supports suspected credential/account compromise and data-exfiltration behaviour.")
print("5. Phishing is a plausible initial-access vector, but it should not be reported as confirmed solely from these logs.")
print("6. Final attribution should remain evidence-based and should be confirmed through preserved forensic evidence.")